#!/usr/bin/env bash
# Generates the remote-talker clip the app's double-talk self-test plays on the speaker
# (app/src/main/res/raw/double_talk_voice.ogg) and its MANIFEST.txt next to this script. Run it
# through the flake, which pins the Piper voice and puts piper, sox and opusenc on PATH:
#
#   nix run .#selftest-clip
#
# Deterministic: Piper runs with its generator noise off (--noise-scale 0 --noise-w-scale 0), sox
# without dither, and opusenc with a fixed Ogg serial number, so the clip depends only on the
# voice, the text and the tool versions. The clip ships inside the APK, so the voice must allow
# redistribution: en_US-ljspeech-medium is MIT-licensed (rhasspy/piper-voices) and was trained from
# scratch on the public-domain LJ Speech dataset. Do not swap in a voice whose dataset forbids it
# (en_US-lessac, for one, is trained on a research-only corpus).
set -euo pipefail

: "${PIPER_VOICES:?run through 'nix run .#selftest-clip', which sets PIPER_VOICES}"
out="${1:-app/src/main/res/raw/double_talk_voice.ogg}"
manifest="${2:-tools/selftest-clip/MANIFEST.txt}"
voice=en_US-ljspeech-medium
model="$PIPER_VOICES/$voice.onnx"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Original text in the manner of a dry, slightly sarcastic test-facility announcer. Sentence pauses
# leave gaps, so the self-test sees the voice alone as well as the user talking over it.
text="Welcome to the audio test chamber. Please talk over me. \
I will not be offended. I am a recording. \
When you speak, the light turns green. When you are quiet, it stays dark. \
If it stays dark while you shout, that is also useful data. \
Cooperation is mandatory."

printf '%s\n' "$text" | piper -m "$model" -c "$model.json" -f "$work/voice.wav" \
    --noise-scale 0 --noise-w-scale 0 --length-scale 0.9 --sentence-silence 0.5 >/dev/null 2>&1
# 48 kHz mono, peaks at -3 dBFS, 0.3 s of lead-in and 1 s of silence before the loop starts over.
# -D: no dither, which is random and would make every run's clip differ.
sox -V1 -D "$work/voice.wav" -b 16 -c 1 -r 48000 "$work/clip.wav" norm -3 pad 0.3 1.0
# Speech at 24 kbit/s is transparent enough for a test talker and keeps the APK small.
opusenc --quiet --serial 1 --bitrate 24 --comp 10 --framesize 20 \
    --title "Mumla double-talk self-test voice" --artist "Piper $voice" "$work/clip.wav" "$out"

{
    echo "# The double-talk self-test's remote talker; generated by tools/selftest-clip/generate.sh."
    echo "# piper-tts ${PIPER_VERSION:-(version unknown)}, sox $(sox --version | sed 's/.*v//'), $(opusenc --version | head -n1)."
    echo "# Flags: --noise-scale 0 --noise-w-scale 0 --length-scale 0.9 --sentence-silence 0.5; sox norm -3,"
    echo "# pad 0.3 1.0, 48 kHz mono;"
    echo "# opusenc --serial 1 --bitrate 24 --comp 10 --framesize 20."
    echo
    echo "[$(basename "$out")]"
    echo "voice: $voice (https://huggingface.co/rhasspy/piper-voices/tree/main/en/en_US/ljspeech/medium)"
    echo "voice license: MIT (rhasspy/piper-voices); trained from scratch on the LJ Speech dataset"
    echo "dataset: LJ Speech 1.1 by Keith Ito and Linda Johnson (https://keithito.com/LJ-Speech-Dataset/), public domain"
    echo "model sha256: $(sha256sum "$model" | cut -d' ' -f1)"
    echo "duration: $(soxi -D "$work/clip.wav") s"
    echo "size: $(stat -c %s "$out") bytes"
    echo "text: $text"
    echo "sha256: $(sha256sum "$out" | cut -d' ' -f1)"
} > "$manifest"
echo "wrote $out ($(stat -c %s "$out") bytes, $(soxi -D "$work/clip.wav") s) and $manifest"
