package se.lublin.humla.net

import com.google.common.truth.Truth.assertThat
import org.junit.Assert.assertThrows
import org.junit.Test
import java.security.cert.CertificateException

class ServerTrustTest {
    private val system = TestCertificates.systemTrust()
    private val authType = "RSA"

    private fun manager(host: String, vararg pinned: TestCertificates.Issued) =
        ServerTrustManager(system, host, pinned.map { CertificatePins.fingerprint(it.certificate) }.toSet())

    @Test
    fun `a system trusted chain naming the host is accepted`() {
        val leaf = TestCertificates.leaf(dnsNames = listOf("mumble.example.org"))
        val tm = manager("mumble.example.org")

        tm.checkServerTrusted(leaf.chain, authType)

        assertThat(tm.failure).isEqualTo(TrustFailure.NONE)
    }

    @Test
    fun `a system trusted chain for another host is not accepted`() {
        val leaf = TestCertificates.leaf(dnsNames = listOf("other.example.org"))
        val tm = manager("mumble.example.org")

        val e = assertThrows(CertificateException::class.java) { tm.checkServerTrusted(leaf.chain, authType) }

        assertThat(e).isNotInstanceOf(CertificateChangedException::class.java)
        assertThat(tm.failure).isEqualTo(TrustFailure.UNTRUSTED)
        assertThat(tm.serverChain).isEqualTo(leaf.chain)
    }

    @Test
    fun `a self signed certificate without a pin is untrusted`() {
        val leaf = TestCertificates.leaf(dnsNames = listOf("mumble.example.org"), selfSigned = true)
        val tm = manager("mumble.example.org")

        assertThrows(CertificateException::class.java) { tm.checkServerTrusted(leaf.chain, authType) }
        assertThat(tm.failure).isEqualTo(TrustFailure.UNTRUSTED)
    }

    @Test
    fun `a pinned self signed certificate is accepted without a host name check`() {
        val leaf = TestCertificates.leaf(selfSigned = true, cn = "Murmur Autogenerated Certificate v2")
        val tm = manager("10.0.0.5", leaf)

        tm.checkServerTrusted(leaf.chain, authType)

        assertThat(tm.failure).isEqualTo(TrustFailure.NONE)
    }

    @Test
    fun `a certificate pinned for one host is not trusted for another`() {
        val leaf = TestCertificates.leaf(selfSigned = true)
        val store = TestCertificates.pinStore("a.example.org" to leaf.certificate)
        val tm = ServerTrustManager(system, "b.example.org", CertificatePins.forHost(store, "b.example.org"))

        assertThrows(CertificateException::class.java) { tm.checkServerTrusted(leaf.chain, authType) }
        assertThat(tm.failure).isEqualTo(TrustFailure.UNTRUSTED)
    }

    @Test
    fun `a pinned host presenting a different certificate reports a change`() {
        val pinned = TestCertificates.leaf(selfSigned = true)
        val presented = TestCertificates.leaf(selfSigned = true)
        val tm = manager("mumble.example.org", pinned)

        val e = assertThrows(CertificateChangedException::class.java) {
            tm.checkServerTrusted(presented.chain, authType)
        }

        assertThat(e.host).isEqualTo("mumble.example.org")
        assertThat(tm.failure).isEqualTo(TrustFailure.CHANGED)
    }

    @Test
    fun `a pinned host moving to a system trusted certificate naming it is accepted`() {
        val pinned = TestCertificates.leaf(selfSigned = true)
        val presented = TestCertificates.leaf(dnsNames = listOf("mumble.example.org"))
        val tm = manager("mumble.example.org", pinned)

        tm.checkServerTrusted(presented.chain, authType)

        assertThat(tm.failure).isEqualTo(TrustFailure.NONE)
    }

    @Test
    fun `a failure is cleared by the next successful check`() {
        val good = TestCertificates.leaf(dnsNames = listOf("mumble.example.org"))
        val bad = TestCertificates.leaf(selfSigned = true)
        val tm = manager("mumble.example.org")
        runCatching { tm.checkServerTrusted(bad.chain, authType) }

        tm.checkServerTrusted(good.chain, authType)

        assertThat(tm.failure).isEqualTo(TrustFailure.NONE)
    }

    @Test
    fun `pins are looked up by host case insensitively`() {
        val leaf = TestCertificates.leaf(selfSigned = true)
        val store = TestCertificates.pinStore("Mumble.Example.org" to leaf.certificate)

        assertThat(CertificatePins.forHost(store, "mumble.example.org."))
            .containsExactly(CertificatePins.fingerprint(leaf.certificate))
        assertThat(CertificatePins.forHost(store, "example.org")).isEmpty()
        assertThat(CertificatePins.forHost(null, "example.org")).isEmpty()
    }

    @Test
    fun `host names match subjectAltNames per RFC 6125`() {
        val cert = TestCertificates.leaf(
            dnsNames = listOf("Mumble.Example.org", "*.voice.example.org", "*.com", "a*.example.net"),
            ipAddresses = listOf("192.0.2.7", "2001:db8::1"),
            cn = "cn-only.example.org",
        ).certificate
        fun m(host: String) = HostnameMatcher.matches(host, cert)

        assertThat(m("mumble.example.org")).isTrue()
        assertThat(m("MUMBLE.EXAMPLE.ORG.")).isTrue()
        assertThat(m("eu.voice.example.org")).isTrue()
        assertThat(m("a.eu.voice.example.org")).isFalse()
        assertThat(m("voice.example.org")).isFalse()
        assertThat(m("example.com")).isFalse()
        assertThat(m("ab.example.net")).isFalse()
        assertThat(m("cn-only.example.org")).isFalse()
        assertThat(m("192.0.2.7")).isTrue()
        assertThat(m("192.0.2.8")).isFalse()
        assertThat(m("2001:db8:0:0:0:0:0:1")).isTrue()
        assertThat(m("[2001:db8::1]")).isTrue()
        assertThat(m("")).isFalse()
    }

    @Test
    fun `a certificate without subjectAltNames matches nothing`() {
        val cert = TestCertificates.leaf(cn = "mumble.example.org").certificate
        assertThat(HostnameMatcher.matches("mumble.example.org", cert)).isFalse()
    }

    @Test
    fun `ip literals are recognised`() {
        assertThat(HostnameMatcher.isIpLiteral("10.1.2.3")).isTrue()
        assertThat(HostnameMatcher.isIpLiteral("::1")).isTrue()
        assertThat(HostnameMatcher.isIpLiteral("mumble.example.org")).isFalse()
        assertThat(HostnameMatcher.isIpLiteral("abc.onion")).isFalse()
    }
}
