package se.lublin.humla.net

import com.google.common.truth.Truth.assertThat
import org.junit.Assert.assertThrows
import org.junit.Test
import java.security.cert.CertificateException

class ServerTrustTest {
    private val system = TestCertificates.systemTrust()
    private val authType = "RSA"

    private fun manager(host: String, vararg pinned: TestCertificates.Issued) =
        ServerTrustManager(system, host, pinned.map { CertificatePins.fingerprint(it.certificate) }.toSet())

    /** Whether [presented] is trusted for [host] with [pins] pinned for it. */
    private fun check(
        host: String,
        presented: TestCertificates.Issued,
        vararg pins: TestCertificates.Issued,
    ): TrustFailure {
        val tm = manager(host, *pins)
        val thrown = runCatching { tm.checkServerTrusted(presented.chain, authType) }.exceptionOrNull()
        assertThat(thrown == null).isEqualTo(tm.failure == TrustFailure.NONE)
        if (tm.failure == TrustFailure.UNTRUSTED) {
            assertThat(thrown).isInstanceOf(CertificateException::class.java)
            assertThat(thrown).isNotInstanceOf(CertificateChangedException::class.java)
            assertThat(tm.serverChain).isEqualTo(presented.chain)
        }
        return tm.failure
    }

    @Test
    fun `a chain is trusted if the system trusts it for the host or it is pinned`() {
        val host = "mumble.example.org"
        val named = TestCertificates.leaf(dnsNames = listOf(host))
        val selfSigned = TestCertificates.leaf(dnsNames = listOf(host), selfSigned = true)
        val murmur = TestCertificates.leaf(selfSigned = true, cn = "Murmur Autogenerated Certificate v2")

        assertThat(check(host, named)).isEqualTo(TrustFailure.NONE)
        assertThat(check(host, TestCertificates.leaf(dnsNames = listOf("other.example.org"))))
            .isEqualTo(TrustFailure.UNTRUSTED)
        assertThat(check(host, selfSigned)).isEqualTo(TrustFailure.UNTRUSTED)
        // A pin needs no host name check.
        assertThat(check("10.0.0.5", murmur, murmur)).isEqualTo(TrustFailure.NONE)
        // A pinned host may move to a certificate the system trusts for it.
        assertThat(check(host, named, murmur)).isEqualTo(TrustFailure.NONE)
    }

    @Test
    fun `a certificate pinned for one host is not trusted for another`() {
        val leaf = TestCertificates.leaf(selfSigned = true)
        val store = TestCertificates.pinStore("a.example.org" to leaf.certificate)
        val tm = ServerTrustManager(system, "b.example.org", CertificatePins.forHost(store, "b.example.org"))

        assertThrows(CertificateException::class.java) { tm.checkServerTrusted(leaf.chain, authType) }
        assertThat(tm.failure).isEqualTo(TrustFailure.UNTRUSTED)
    }

    @Test
    fun `a pinned host presenting a different certificate reports a change`() {
        val pinned = TestCertificates.leaf(selfSigned = true)
        val presented = TestCertificates.leaf(selfSigned = true)
        val tm = manager("mumble.example.org", pinned)

        val e = assertThrows(CertificateChangedException::class.java) {
            tm.checkServerTrusted(presented.chain, authType)
        }

        assertThat(e.host).isEqualTo("mumble.example.org")
        assertThat(tm.failure).isEqualTo(TrustFailure.CHANGED)
    }

    @Test
    fun `a failure is cleared by the next successful check`() {
        val good = TestCertificates.leaf(dnsNames = listOf("mumble.example.org"))
        val bad = TestCertificates.leaf(selfSigned = true)
        val tm = manager("mumble.example.org")
        runCatching { tm.checkServerTrusted(bad.chain, authType) }

        tm.checkServerTrusted(good.chain, authType)

        assertThat(tm.failure).isEqualTo(TrustFailure.NONE)
    }

    @Test
    fun `pins are looked up by host case insensitively`() {
        val leaf = TestCertificates.leaf(selfSigned = true)
        val store = TestCertificates.pinStore("Mumble.Example.org" to leaf.certificate)

        assertThat(CertificatePins.forHost(store, "mumble.example.org."))
            .containsExactly(CertificatePins.fingerprint(leaf.certificate))
        assertThat(CertificatePins.forHost(store, "example.org")).isEmpty()
        assertThat(CertificatePins.forHost(null, "example.org")).isEmpty()
    }

    @Test
    fun `host names match subjectAltNames per RFC 6125`() {
        val cert = TestCertificates.leaf(
            dnsNames = listOf("Mumble.Example.org", "*.voice.example.org", "*.com", "a*.example.net"),
            ipAddresses = listOf("192.0.2.7", "2001:db8::1"),
            cn = "cn-only.example.org",
        ).certificate
        fun m(host: String) = HostnameMatcher.matches(host, cert)

        assertThat(m("mumble.example.org")).isTrue()
        assertThat(m("MUMBLE.EXAMPLE.ORG.")).isTrue()
        assertThat(m("eu.voice.example.org")).isTrue()
        assertThat(m("a.eu.voice.example.org")).isFalse()
        assertThat(m("voice.example.org")).isFalse()
        assertThat(m("example.com")).isFalse()
        assertThat(m("ab.example.net")).isFalse()
        assertThat(m("cn-only.example.org")).isFalse()
        assertThat(m("192.0.2.7")).isTrue()
        assertThat(m("192.0.2.8")).isFalse()
        assertThat(m("2001:db8:0:0:0:0:0:1")).isTrue()
        assertThat(m("[2001:db8::1]")).isTrue()
        assertThat(m("")).isFalse()
    }

    @Test
    fun `a certificate without subjectAltNames matches nothing`() {
        val cert = TestCertificates.leaf(cn = "mumble.example.org").certificate
        assertThat(HostnameMatcher.matches("mumble.example.org", cert)).isFalse()
    }

    @Test
    fun `ip literals are recognised`() {
        assertThat(HostnameMatcher.isIpLiteral("10.1.2.3")).isTrue()
        assertThat(HostnameMatcher.isIpLiteral("::1")).isTrue()
        assertThat(HostnameMatcher.isIpLiteral("mumble.example.org")).isFalse()
        assertThat(HostnameMatcher.isIpLiteral("abc.onion")).isFalse()
    }
}
