#!/usr/bin/env bash
# Generates the speech clips the humla device tests use as talkers (see
# libraries/humla/src/testSpeech/speech/MANIFEST.txt). Run it through the flake, which pins the
# Piper voices and puts piper, sox and coreutils on PATH:
#
#   nix run .#speech-corpus
#
# Piper runs with its generator noise off (--noise-scale 0 --noise-w-scale 0), so a clip depends
# only on the voice, the text and the onnxruntime build. The clips are committed; nothing generates
# them at build time.
set -euo pipefail

: "${PIPER_VOICES:?run through 'nix run .#speech-corpus', which sets PIPER_VOICES}"
out="${1:-libraries/humla/src/testSpeech/speech}"
seconds=12
mkdir -p "$out"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

manifest="$out/MANIFEST.txt"
{
    echo "# Speech corpus for the humla device tests; generated by tools/speech-corpus/generate.sh."
    echo "# piper-tts ${PIPER_VERSION:-(version unknown)}, sox $(sox --version | sed 's/.*v//')."
    echo "# Flags: --noise-scale 0 --noise-w-scale 0 --sentence-silence 0.35; mono PCM16 at the voice's"
    echo "# native rate, 0.2 s of lead-in, cut or padded to ${seconds} s, 50 ms fade-out (clips loop)."
    echo
} > "$manifest"

# clip <name> <voice> <text>
clip() {
    local name="$1" voice="$2" text="$3"
    local model="$PIPER_VOICES/$voice.onnx"
    printf '%s\n' "$text" | piper -m "$model" -c "$model.json" -f "$work/$name.wav" \
        --noise-scale 0 --noise-w-scale 0 --sentence-silence 0.35 >/dev/null 2>&1
    # The tail pad is cut again by trim, which sox reports as a warning; -V1 keeps only errors.
    # -D: no dither, which is random and would make every run's clips differ.
    sox -V1 -D "$work/$name.wav" -b 16 -c 1 "$out/$name.wav" pad 0.2 "$seconds" trim 0 "$seconds" \
        fade t 0 "$seconds" 0.05
    {
        echo "[$name.wav]"
        echo "voice: $voice"
        echo "model sha256: $(sha256sum "$model" | cut -d' ' -f1)"
        echo "rate: $(soxi -r "$out/$name.wav") Hz"
        echo "text: $text"
        echo "sha256: $(sha256sum "$out/$name.wav" | cut -d' ' -f1)"
        echo
    } >> "$manifest"
    echo "wrote $out/$name.wav"
}

# Far end: two male voices. Near end: two female voices.
clip far_de_m de_DE-thorsten-medium \
    "Guten Morgen zusammen, ich hoffe, ihr hört mich gut. Wir fangen gleich mit dem ersten Punkt an. \
Gestern Abend ist der Server zweimal neu gestartet, und niemand weiß genau, warum. \
Ich habe die Protokolle angesehen, aber noch nichts Auffälliges gefunden. \
Kann bitte jemand heute Nachmittag noch einmal nachsehen?"
clip far_en_m en_US-ryan-medium \
    "Good morning everyone, I hope you can all hear me clearly. Let's start with the first item on the list. \
The build broke twice last night, and nobody is quite sure why. \
I looked through the logs, but nothing obvious turned up. \
Could someone take another look this afternoon?"
clip near_de_f de_DE-kerstin-low \
    "Ja, ich kann das übernehmen, aber erst nach dem Mittagessen. \
Mir ist aufgefallen, dass die Verbindung jeden Abend kurz nach zehn abbricht. \
Vielleicht hängt das mit der Sicherung zusammen, die um diese Zeit läuft. \
Ich melde mich, sobald ich mehr weiß."
clip near_en_f en_US-lessac-medium \
    "Yes, I can take that, but only after lunch. \
I noticed that the connection drops every evening just after ten o'clock. \
Maybe it has something to do with the backup that runs at that time. \
I will get back to you as soon as I know more."
