/*
 * Copyright (C) 2026 The Mumla Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package se.lublin.mumla.audio

import android.content.Context
import android.media.AudioManager
import android.media.MediaCodec
import android.media.MediaExtractor
import android.media.MediaFormat
import androidx.annotation.RawRes
import se.lublin.humla.audio.DoubleTalkSelfTest
import se.lublin.humla.audio.SelfTestReading
import se.lublin.humla.audio.capture.EchoCancellationMode
import se.lublin.humla.audio.routing.AudioDeviceCategory
import se.lublin.mumla.R
import se.lublin.mumla.Settings
import java.io.IOException
import java.nio.ByteOrder

/**
 * The test voice, `res/raw/double_talk_voice.ogg` (Opus, generated by
 * `tools/selftest-clip/generate.sh`), decoded to 48 kHz mono PCM with the platform's codec.
 */
object SelfTestVoice {
    private const val RATE = 48_000
    private const val TIMEOUT_US = 10_000L

    /** @throws IOException when the clip cannot be read or is not 48 kHz Opus. */
    fun decode(context: Context, @RawRes clip: Int = R.raw.double_talk_voice): ShortArray {
        val extractor = MediaExtractor()
        try {
            context.resources.openRawResourceFd(clip).use {
                extractor.setDataSource(it.fileDescriptor, it.startOffset, it.length)
            }
            val track = (0 until extractor.trackCount).firstOrNull {
                extractor.getTrackFormat(it).getString(MediaFormat.KEY_MIME)?.startsWith("audio/") == true
            } ?: throw IOException("no audio track in the test voice")
            extractor.selectTrack(track)
            return decodeTrack(extractor, extractor.getTrackFormat(track))
        } finally {
            extractor.release()
        }
    }

    private fun decodeTrack(extractor: MediaExtractor, format: MediaFormat): ShortArray {
        val codec = MediaCodec.createDecoderByType(requireNotNull(format.getString(MediaFormat.KEY_MIME)))
        val out = ShortArrayBuilder()
        try {
            codec.configure(format, null, null, 0)
            codec.start()
            val info = MediaCodec.BufferInfo()
            var inputDone = false
            var channels = format.getInteger(MediaFormat.KEY_CHANNEL_COUNT)
            while (true) {
                if (!inputDone) {
                    val index = codec.dequeueInputBuffer(TIMEOUT_US)
                    if (index >= 0) {
                        val buffer = requireNotNull(codec.getInputBuffer(index))
                        val size = extractor.readSampleData(buffer, 0)
                        if (size < 0) {
                            codec.queueInputBuffer(index, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)
                            inputDone = true
                        } else {
                            codec.queueInputBuffer(index, 0, size, extractor.sampleTime, 0)
                            extractor.advance()
                        }
                    }
                }
                val index = codec.dequeueOutputBuffer(info, TIMEOUT_US)
                if (index == MediaCodec.INFO_OUTPUT_FORMAT_CHANGED) {
                    val output = codec.outputFormat
                    channels = output.getInteger(MediaFormat.KEY_CHANNEL_COUNT)
                    val rate = output.getInteger(MediaFormat.KEY_SAMPLE_RATE)
                    if (rate != RATE) throw IOException("the test voice decodes at $rate Hz, not $RATE")
                } else if (index >= 0) {
                    val buffer = requireNotNull(codec.getOutputBuffer(index)).order(ByteOrder.nativeOrder())
                    buffer.position(info.offset)
                    buffer.limit(info.offset + info.size)
                    val samples = buffer.asShortBuffer()
                    // Keep the first channel only; the clip is mono, a stereo decode duplicates it.
                    while (samples.remaining() >= channels) {
                        out.add(samples.get())
                        repeat(channels - 1) { samples.get() }
                    }
                    codec.releaseOutputBuffer(index, false)
                    if (info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0) break
                }
            }
        } catch (e: IllegalStateException) {
            throw IOException("the platform could not decode the test voice", e)
        } finally {
            codec.release()
        }
        return out.toArray()
    }

    private class ShortArrayBuilder {
        private var data = ShortArray(RATE * INITIAL_SECONDS)
        private var size = 0

        fun add(value: Short) {
            if (size == data.size) data = data.copyOf(data.size * 2)
            data[size++] = value
        }

        fun toArray(): ShortArray = data.copyOf(size)
    }

    private const val INITIAL_SECONDS = 24
}

/** The real tests: the user's settings, the speaker's echo canceller, the shipped voice. */
class AndroidSelfTestEngines(private val context: Context) : SelfTestEngineFactory {
    /** Decoded once per screen; about 2 MB. */
    private var voice: ShortArray? = null

    override fun create(onReading: (SelfTestReading) -> Unit): SelfTestEngine {
        val clip = voice ?: SelfTestVoice.decode(context).also { voice = it }
        val settings = Settings.getInstance(context)
        // The test plays on the speaker, so it runs the canceller the user has for the speaker.
        val echo = if (settings.isEchoCancellationEnabled(AudioDeviceCategory.SPEAKER)) {
            EchoCancellationMode.WEBRTC
        } else {
            EchoCancellationMode.NONE
        }
        val test = DoubleTalkSelfTest(
            context.getSystemService(AudioManager::class.java),
            settings.vadConfig,
            settings.noiseSuppressionMode,
            settings.speexNoiseSuppressDb,
            echo,
            settings.androidAudioEffects,
            settings.rnnoiseAttenuationLimitDb,
            clip,
            onReading,
        )
        return object : SelfTestEngine {
            override val echoCancelled: Boolean get() = test.echoCancelled
            override fun start() = test.start()
            override fun stop() = test.stop()
            override fun setAttenuationLimitDb(limitDb: Float) = test.setAttenuationLimitDb(limitDb)
        }
    }
}
